### ISSUE TITLE
Section 5 - Scoping - Feb 6th

### ISSUE THREAD

**Issue by argo49** [argo49/soen-scheduler#13]
With regard to the cost/time necessary to meet all the goal presented in section 3, and given the resources  available presented in section 4, give here the scope of the solution that you will implement in the project.
List all features/goals/qualities that will be left out because of lack of time/resources.

**Comment by niofire** [comment]
# Essential Features
- [x] Generation of schedule
- [x] Validation of schedule through course sequence
- [x] Some kind of login feature (MyConcordia/Independent?)

# Nonessential Features
- [ ] Automatic registration after schedule generation - NEED DISCUSSION
- [x] Display of the courses that the student needs to take in order to complete degree
- [x] Show other students who are registered in the course sections
- [ ] Waiting list + immediate registration feature - NEED DISCUSSION
- [x] Compatibility with many devices and browsers
- [x] Rate My Professor integration
- [ ] Sound Effects
- [ ] https security - NEED DISCUSSION
- [ ] imail, google calendar integration
- [ ] 3D graphics
- [x] forgot password system
- [ ] captcha
- [ ] offline/online modes
- [x] Save and compare chosen schedules
- [ ] Guest account
- [x] Facebook Login
- [ ] Load schedule by pdf
- [x] Save to pdf
- [x] print schedule
- [x] student preferences
- [x] Share on facebook
- [x] Like on facebook
