### ISSUE TITLE
Format Deliverable 1 (make it look pretty)

### ISSUE THREAD

**Issue by argo49** [argo49/soen-scheduler#17]
Use the color palette and fonts and add logos and ~~pretty sparkles~~ images and other nice things.

Fonts:
- Headers:    Gill Sans MT Pro Light
- Body Text:  Arial

**Comment by c-robi** [comment]
Off-topic: If you are receiving a million updates from GitHub (like this one), make sure to go to your profile settings and disable email notifications for issues you don't follow!

On-topic: For folks working on documentation, are we sticking with Google Docs? We can't use Gill Sans MT Pro Light with it (oh no!!) and our options are much more limited if we're using it. For instance, tables have way less customization, as I have just noticed... If we need stuff like list of figures and tables or anything advanced, we'd end up doing them manually. Of course, not using Google Docs is less practical.
My idea is to compile the actual content/text in Google Doc (little formatting) and then have someone implement that into Word when it's done, so that the fluffiness can be added then. But that's, well, slow.
Thoughts?

**Comment by coolhatharry** [comment]
I personally prefer working on Google docs, we just need assign somebody to make it pretty in word.

**Comment by glachov** [comment]
About the logo: It doesn't need to be something complicated but it needs to send some message.  We cloud use just the first letter of the team's name "A" or "A +" with a slogan like "Better Scheduling, Better  Grades"? I played around with the A close to the font Arial and I've  tried to use the color scheme, so it could be something like the attached below. We need to choose the colors of the logo and slogan if we decide to have some. What do you think?
![logo a plus](https://f.cloud.github.com/assets/6385357/2056443/302a91c2-8adc-11e3-9785-deec730507d9.png)

**Comment by AmmarBaali** [comment]
I just made a few changes to Deliverable 1. I made a copy of the old doc "Deliverable 1" (now called "[Outdated] Deliverable 1" so you guys can go back to before if you wish to. I basically did restructuring of some sentences, formatting, etc.
