### ISSUE TITLE
Web Design Mockup

### ISSUE THREAD

**Issue by argo49** [argo49/soen-scheduler#4]
A quick mockup of the design for the site. Will feature some minor functionality (JavaScript swoops etc.).

Will be viewable at [tylerargo.com/argonauts](http://tylerargo.com/argonauts) sometime this weekend (Jan 18-19).

**Comment by ghost** [comment]
I just want  to tell you guys that i found the UML Tutorial and i think it
is useless, so i will not upload the file. But i see this website from the
teacher's lecture note is much better:
http://www.comptechdoc.org/independent/uml/begin/umldomainmodel.html

**Comment by niofire** [comment]
hey everyone, sorry again for missing that meeting.I was wondering how we were separating the workload? Are we "checking out" documentation elements that we want to work on or everything has already been separated at the meeting?
Thanks!Date: Fri, 17 Jan 2014 12:35:22 -0800

**Comment by c-robi** [comment]
Here's a summary of the meeting!

We decided that Evangelia and Tyler can work on a basic server and client respectively, so that we have a prototype to help us visualize our ideas. The rest of the team does Deliverable 1. I have uploaded a document called Deliverable 1 sections where we can volunteer to do one of the sections. However, we cannot really start this document yet because we need a brainstorm session! That's why on Wednesday at noon, we will have a meeting to pick the features we want to include in the project.

Also important, we decided to try out Campfire as our chatting tool, so make sure you open your account for that: Tyler should have sent everyone an invitation.

**Comment by argo49** [comment]
The first version is live @ [tylerargo.com/argonauts](http://tylerargo.com/argonauts)

Still needs work though, will add more stuff before Wednesday.

**Comment by c-robi** [comment]
I like the style of the site a lot. The code itself is fairly light, too, from what I see. It'll give us a nice preview for Wednesday! My only concern is for a mobile version should we choose to implement one: it might require some rearranging for the left tab because of vertical screens. Of course, that's only if we choose to care about mobile.

Can you share with us which libraries you are using? I recognize jQuery and jQuery UI, so I can describe them for team members that are not familiar:

jQuery: It's another way of writing JavaScript to make accessing HTML elements simpler than with native functions. For example, you probably know this annoying function:
var title = document.getElementById("title");
In jQuery, you can instead access it by using a CSS selector:
var title = $("#title");
With this jQuery object, you can then use a variety of simple functions to modify the object's CSS properties, animations and other things. They are documented here: http://api.jquery.com/

jQuery UI: This uses the above library. It allows you to easily insert pre-defined elements (widgets) in your webpage, like a dropdown menu, tabs, a date picker, etc. so you can save a lot of time. It also provides UI effects in general, which I am much less familiar with. Official site is here: http://jqueryui.com/
