### ISSUE TITLE
Section 3 - Goals and Constraints - Feb 10th

### ISSUE THREAD

**Issue by c-robi** [argo49/soen-scheduler#7]
Hello folks,

I was trying to figure out how to divide section 3 in Deliverable 1 and thought instructions were a little vague. I'm opening this issue so that we can agree on something, and possibly to divide the sections. Here's what I understand from each section so far:

3.1 Functional Requirements
Not sure why this isn't named "Bunch of Use Cases". The instructions specify "Each individual requirement shall be presented as a use case". We need to draw a use case model and describe each use case in a table. Many teams have not done this exactly, though, because they added an actual functional requirements lists. To me, the lists looked redundant, but I'm not sure what to think about this. Maybe the professors liked it?

3.2 Domain Model
Put the domain model and add an explanation for each individual object contained in here. We need to also explain the relationships of the different objects.

3.3 Constraints and Qualities
Add in requirements such as performance, useability, security, etc. In other words, this includes anything that isn't a functional requirement (i.e. it can't be described as a use case). No team has used plain text for this, they used lists. Probably because it's easier to cross out requirements that way...

What are your thoughts?

(Also, I'll try to work mostly on 3.1, since it seems pretty big.)

**Comment by coolhatharry** [comment]
I started doing section 3.3, so I'll keep doing it.

**Comment by c-robi** [comment]
I'm going to define a bunch of use cases for 3.1 then. They are in the document entitled List of Possible Use Cases on Google Drive. This will give people working for the later sections something to start with even if it isn't perfect.

**Comment by MWarsame** [comment]
![ucdiagram](https://f.cloud.github.com/assets/3186705/2056478/3e042776-8add-11e3-9e76-70a1072fb1b0.png)
Here is the use case diagram for the student system.  Feel free to let me know where I can make improvements.

**Comment by c-robi** [comment]
Hey Mather, here's a few things I noticed:
- Use case numbers have to be changed to reflect the new order in Google Doc (see paragraph below for the reason).
- The other actors aren't pointing to their use cases, such as login/logout, schedule changing and forcing student into a section. In the Google Doc you can just look at the Actor line to know which actors point to what cases
- I think the use case diagram also has to include the databases used?

I have been working on the use case tables earlier and did the following changes: some numbers are shuffled around because the use cases must be in order of importance (very annoying...), and I merged all four cases of Modifying a Student Schedule into one use case valid for all four users. To me, it reduces clutter significantly, but I can revert the changes if people disagree. Please make sure to check the new order of use cases.

**Comment by MWarsame** [comment]
Sounds good, I'll definitely have to add the database. Wasn't sure whether
or not to allow the admin and director access to the student specific use
cases, because the extent of our project is "a personal academic schedule
designer". Allowing access to certain use cases would make it a
registration tool. I can make the use case diagram for the director, admin
and registrar separate from the student system diagram for the most part
each use case can be attributed to a specific user.

**Comment by argo49** [comment]
I don't know if that's the final diagram style, but if keeping it clutter-free is an issue, you could use [lucid charts](https://www.lucidchart.com/) which has a really good knack for doing the arrows cleanly (and it would make it look more like our domain model too! Branding! :D)

**Comment by c-robi** [comment]
Mather, you have a good point about the software becoming a registration tool if we allow certain use cases. Many use cases we have imply that it's a registration tool of some sort, most notably:
- There are users like the administrator and registrar, which have no purpose if they cannot access/change student schedules (it's their only use case);
- Argo knows when a class is full, which is difficult to do if it doesn't have access to the official list of students in the section;
- The waiting list's purpose is to register a student into a course when there's room;
- The program director can force you into a section that's full, which is pointless outside of the official registration tool.

So yeah, I don't know what the description means anymore. If it's just a personal designer for students, why are there actors other than Student in the domain model?

**Comment by c-robi** [comment]
Just leaving a note that all the use cases of 3.1 have text in them, so they're complete for the purposes of finishing all other sections. They are not perfect since most of the steps are made up (we don't know the user interface yet) and might be missing a few details. At worst, we change them for future deliverables. Mather, can you place the use case model before the individual tables in the document when it's finished?

**Comment by MWarsame** [comment]
I'll switch to lucidchart, ArgoUML doesn't have that feature.

I had a look at bacon's use case diagrams; they had program director
inheriting from student and made a second use case diagram for the program
director specific use cases. In our case (and in most cases) the student
can interact with the database through proxy of the program director and
administrator. In practice we can have the student and database be the only
actors in the system, because the program director and administrator can
only alter the students state through the database.

**Comment by MWarsame** [comment]
![ucd - new page](https://f.cloud.github.com/assets/3186705/2094670/c56ffc5c-8ed0-11e3-9799-aea87e6e6629.png)

I left out the database and other actors from the use case diagram. I only represented the surface level behaviors from the student’s perspective. The database is an internal component of our system, since the application isn’t going to be communicating with an external database we wont need to represent it as an actor. As for the admin, director and registrar I guess we still remain undecided about that… 
Our use case diagram should represent the “non-technical” aspects of the application. It would be a component diagram that represents the users interactions to the admin, director, and registrar. As for the database we would have to make a sequence diagram to demonstrate the processes that are done by the user.

**Comment by c-robi** [comment]
Looks nice! Only detail is U9's text is cut short for some reason.

Now I'm wondering, does everyone agree on ditching the other actors and only keeping Student? If we do, I'll go over the use cases and fix that up during the weekend. It also means that we probably ditch U12, Forcing Student into a Section, so it would change the numbers on the use cases (again... sadly) and modify the domain model somewhat. I do think only keeping Student is more pertinent even though it involves these adjustments.

**Comment by c-robi** [comment]
I changed three things in the use cases:
- U14 (Forcing Student into Section) is gone and subsequent use cases are numbered accordingly
- The name of every use case now uses the present tense (the course slides explicitly say to do this)
- Any reference to other actors than Student is removed.
  @MWarsame and @niofire : When you update your respective section, please make sure that the names/numbers match these new names/numbers. I'm pretty sure they will never change again from this point on.
